name: Release Docker
on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  release:
    types: [published]
jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: khulnasoft/golang-buf
    - uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        platforms: "linux/arm64,linux/amd64"
        labels: ${{ steps.meta.outputs.labels }}
